### ISSUE TITLE
Compare two primer/amplicon filter options

### ISSUE THREAD

**Issue by iqbal-lab** [iqbal-lab-org/viridian_workflow#81]
Scheme 1 (current code): never trust the primer bases of a read

Scheme 2: 
 - If at a position there is only one amplicon, take the sequence from it, whether or not it is in a primer
 - If there are two overlapping amplicons at this position, but one has a primer, ignore the sequence containing primers, so use the data from the amplicon with no primer to make a consensus
 - if there are two overlapping amplicons at this position, but no primer there in either, use the amplicon-bias filter to insist they agree.

We have all the code to turn scheme 2 on, will run both and compare.

**Comment by iqbal-lab** [comment]
In this https://github.com/iqbal-lab-org/viridian_workflow/issues/81#issuecomment-1190317999
do you mean the amplicon bias is primer aware or not? We still want to prefer non-primer seq when we have that

**Comment by iqbal-lab** [comment]
I find the last comment a bit confusing, will grab you when we are both in tomorrow. not sure what you are saying is the basis of the current strategy, and given we are mid refactor, not sure what "current" is meant here. Please don't go ahead with this until we've both understood each other and i've agreed to it. I think we already have the code for scheme 2 also, which is the alternative i want to test

**Comment by jeff-k** [comment]
The current strategy is to not consider bases that are called inside the primer sequences of a read. This has always been the approach but it has only been properly done post v0.3.7. This is the same logic behind primer trimming. It was justified by observed ref reversions in the pileup-based variation calling pipelines.

The unsatisfactory part of this strategy is that we miss out on true-negative reference base calls when an amplicon has dropped and the adjacent amplicon's primer region gets ignored by us. It may make sense to consider these primer base calls, though, because some primer schemes may include alternate primers for alternate alleles. So in theory we could miss a true-positive variant call too. In other words, that primer trimming is not appropriate here.

If we accept the logic that primer bases are just as good as the others then we can get the desired behaviour by switching off the primer base filter and enabling the amplicon bias filter. The difference between this proposal and scheme 2 is the idea that primer bases are good, but not as good as the other base calls. Scheme 2 would selectively consider them when there isn't any other evidence to consider.

This is a good idea, but it would add an extra layer of sophistication to our variant calling step. This would be a lot of work and we'd need to design an experiment to test its effectiveness. An alternative is that we can test whether treating primer bases as "just as good" now, with code that already exists, and see if that works.

**Comment by iqbal-lab** [comment]
Re "If we accept the logic that primer bases are just as good..."

i don't accept the logic that primer bases are just as good now, I explicitly want a gradation from non-primer trusted, to primer less trusted but more information than nothing.

**Comment by jeff-k** [comment]
I agree that there is gradation of trust in the bases. It is between zero (our policy now) and total (my proposed experiment that we can do now).

From a practical perspective, it makes sense to test those two extremes right now. We are ready to without any additional development time.

To proceed further, we could then define what our desired TPR vs. FNR trade-off is and then design an experiment to evaluate more sophisticated models.

**Comment by iqbal-lab** [comment]
Let's talk tomorrow when we get in

**Comment by jeff-k** [comment]
Scheme 2 is implemented now. The internal pileup datastructure counts the unique profiles of the base calls at a position, the `BaseProfile` struct. This includes whether the base was read from inside the read's primers. These profiles are counted per overlapping amplicon, so we're able to decide whether or not the bases should be counted if they're in a primer and the pileup position has more than 1 overlapping amplicon.
